#!/usr/bin/env bash

HELP_USAGE="For help, run: ${0} --help"
NAME_USAGE="<NAME> cannot be empty"
PREFIX_USAGE="<PREFIX> cannot be empty"
USAGE="\
Usage:
  ${0} [OPTIONS] -- <NAME>

${NAME_USAGE}

OPTIONS:
  -h, --help              Show this help
  -u, --uppercase         Uppercase the <NAME>
  -p, --prefix <PREFIX>   Change the greeting prefix"

uppercase_option="false"
prefix_option="Hello"
name=""
backwards_name=""
today=""
output=""

uppercase() {
  echo "$(tr '[:lower:]' '[:upper:]' <<< ${1})"
}

reverse() {
  echo "$(rev <<< ${1})"
}

get_today() {
  echo "$(date '+%F')"
}

get_duration() {
  echo "${SECONDS}"
}

handle_help() {
  echo -e "${USAGE}"
  exit 0
}

handle_empty_arg() {
  if [[ -z "${2}" ]]; then
    echo "${1}"
    echo "${HELP_USAGE}"
    exit 1
  fi
}

handle_unknown_option() {
  echo "Unknown option: ${1}"
  echo "${HELP_USAGE}"
  exit 1
}

while [[ ${#} -gt 0 ]]; do
  case ${1} in
    -h | --help)
      handle_help
      ;;
    -u | --uppercase)
      uppercase_option="true"
      shift
      ;;
    -p | --prefix)
      shift
      prefix_option="${1}"
      handle_empty_arg "${PREFIX_USAGE}" "${prefix_option}"
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      handle_unknown_option "${1}"
      ;;
  esac
done

name=${1}

if [[ -p /dev/stdin ]]; then
  name="$(cat -)"
fi

handle_empty_arg "${NAME_USAGE}" "${name}"

if [[ ${uppercase_option} == "true" ]]; then
  name=$(uppercase ${name})
fi

backwards_name="$(reverse ${name})"
today="$(get_today)"
duration="$(get_duration)"

output="\
${prefix_option}, ${name}
Your name backwards is ${backwards_name}
Today is ${today}"

echo "${output}"
echo "Completed in ${duration} s"
