#!/usr/bin/env python

import sys
import time
import datetime

SCRIPT_NAME = "./script"
HELP_USAGE = "For help, run: {0} --help"
NAME_USAGE = "<NAME> cannot be empty"
PREFIX_USAGE = "<PREFIX> cannot be empty"
USAGE = """\
Usage:
  {0} [OPTIONS] -- <NAME>

{1}

OPTIONS:
  -h, --help              Show this help
  -u, --uppercase         Uppercase the <NAME>
  -p, --prefix <PREFIX>   Change the greeting prefix"""

start_time = time.time()
args = sys.argv[1:]
skip_next_iteration = False
seperator_index = None

uppercase_option = False
prefix_option = "Hello"
name = ""
backwards_name = ""
today = ""
output = ""
duration = None


def handle_help():
    print(USAGE.format(SCRIPT_NAME, NAME_USAGE))
    sys.exit(0)


def die():
    print(HELP_USAGE.format(SCRIPT_NAME))
    sys.exit(1)


def handle_unknown_option(arg):
    print("Unknown option: {0}".format(arg))
    die()


def get_prefix_option(index):
    try:
        return args[index]
    except IndexError:
        print(PREFIX_USAGE)
        die()


def handle_name_usage():
    print(NAME_USAGE)
    die()


def get_name(index):
    try:
        return args[index]
    except IndexError:
        return ""


def stdin_exists():
    return not sys.stdin.isatty()


def get_stdin():
    return sys.stdin.read().strip()


def reverse(str):
    return str[::-1]


def get_today():
    return datetime.date.today().strftime("%Y-%m-%d")


def get_duration_in_seconds(start_time, end_time):
    return round((end_time - start_time) * 1000, 2)


for i, arg in enumerate(args):
    if skip_next_iteration == True:
        skip_next_iteration = False
        continue
    elif arg == "-h" or arg == "--help":
        handle_help()
    elif arg == "-u" or arg == "--uppercase":
        uppercase_option = True
    elif arg == "-p" or arg == "--prefix":
        prefix_option = get_prefix_option(i + 1)
        skip_next_iteration = True
        continue
    elif arg == "--":
        name = get_name(i + 1)
        break
    else:
        handle_unknown_option(arg)

if stdin_exists():
    name = get_stdin()

if name == "":
    handle_name_usage()

if uppercase_option == True:
    name = name.upper()

backwards_name = reverse(name)
today = get_today()

output = """\
{0}, {1}
Your name backwards is {2}
Today is {3}"""

print(output.format(prefix_option, name, backwards_name, today))

duration = get_duration_in_seconds(start_time, time.time())

print("Completed in {0} s".format(duration))
